# Generated by Django 3.2.3 on 2021-05-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('Ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('Ingredient_image', models.ImageField(upload_to='images/Ingredients/')),
                ('Type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('Receipe_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Fats', models.TextField()),
                ('Calories', models.TextField()),
                ('Quantity', models.TextField()),
                ('Proteins', models.TextField()),
                ('Carbohydrates', models.TextField()),
                ('Receipe_Image', models.ImageField(upload_to='images/Receipe')),
                ('Category_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproj.category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('Receipe_Ingredient_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Ingredient_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproj.ingredients')),
                ('Receipe_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproj.recipes')),
            ],
        ),
    ]
